# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 223)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: #3D3D3D;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 130, 371, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid #A4004D;\n"
"background-color: #444444;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 2px solid white;\n"
"background-color: #444444;\n"
"color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 170, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 3px;\n"
"  background: linear-gradient(rgb(110,112,120), rgb(81,81,86)) rgb(110,112,120);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: linear-gradient(rgb(126,126,134), rgb(70,71,76)) rgb(126,126,134);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: linear-gradient(rgb(76,77,82), rgb(56,57,62)) rgb(76,77,82);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 371, 28))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 10, 371, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"border: 2px solid #A4004D;\n"
"background-color: #404040;\n"
"color: white;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать папку для сохранения"))
        self.pushButton_2.setText(_translate("MainWindow", "Скачать"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/VideoID"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Процесс выполнения.."))
